# versionは3系が最新版で、versionによって書き方が異なる

# golang:         コンテナ名
# build:          **((Dockerfileが存在する場所))**
# image:          イメージの名前
# container_name: コンテナの名前
# volumes:        「./a:/b」 aはホスト側のフォルダを　bのdockerコンテナ側へ
# ports:          ポート
# environment:    環境変数
# tty: true       コンテナ起動永続化
# links:          他のコンテナの接続

version: '3'
services:
  python:
    build: ./src/
    image: umbrella_python
    container_name: umbrella_report
    volumes:
      - ./src:/python/src
      - /root/webAPI/logFiles:/python/src/logFiles
    working_dir: '/python/src'

    tty: true

    restart: always
